// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<FacturXResultStringVecU8> extractXml({
  required List<int> pdfBytes,
  required bool checkXsd,
}) => RustLib.instance.api.crateApiExtractXml(
  pdfBytes: pdfBytes,
  checkXsd: checkXsd,
);

Future<FacturXResultVecU8> generateFacturx({
  required List<int> pdfBytes,
  required List<int> xmlBytes,
  required GenerateConfig config,
}) => RustLib.instance.api.crateApiGenerateFacturx(
  pdfBytes: pdfBytes,
  xmlBytes: xmlBytes,
  config: config,
);

Future<FacturXResultFlavor> getFlavor({required List<int> xmlBytes}) =>
    RustLib.instance.api.crateApiGetFlavor(xmlBytes: xmlBytes);

Future<Uint8List> unpackResultVec({required FacturXResultVecU8 result}) =>
    RustLib.instance.api.crateApiUnpackResultVec(result: result);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FacturXResult < Flavor >>>
abstract class FacturXResultFlavor implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FacturXResult < (String , Vec < u8 >) >>>
abstract class FacturXResultStringVecU8 implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FacturXResult < Vec < u8 > >>>
abstract class FacturXResultVecU8 implements RustOpaqueInterface {}
