// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'lib.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FacturXResultFlavorPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavorPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FacturXResultStringVecU8Ptr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8Ptr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FacturXResultVecU8Ptr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8Ptr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SystemTimePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTimePtr;

  @protected
  FacturXResultFlavor
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor(
    dynamic raw,
  );

  @protected
  FacturXResultStringVecU8
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8(
    dynamic raw,
  );

  @protected
  FacturXResultVecU8
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
    dynamic raw,
  );

  @protected
  SystemTime
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    dynamic raw,
  );

  @protected
  Map<String, Attachment> dco_decode_Map_String_attachment_None(dynamic raw);

  @protected
  FacturXResultFlavor
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor(
    dynamic raw,
  );

  @protected
  FacturXResultStringVecU8
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8(
    dynamic raw,
  );

  @protected
  FacturXResultVecU8
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
    dynamic raw,
  );

  @protected
  SystemTime
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Attachment dco_decode_attachment(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  SystemTime
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    dynamic raw,
  );

  @protected
  Flavor dco_decode_box_autoadd_flavor(dynamic raw);

  @protected
  GenerateConfig dco_decode_box_autoadd_generate_config(dynamic raw);

  @protected
  Level dco_decode_box_autoadd_level(dynamic raw);

  @protected
  OrderXType dco_decode_box_autoadd_order_x_type(dynamic raw);

  @protected
  PdfMetadata dco_decode_box_autoadd_pdf_metadata(dynamic raw);

  @protected
  Flavor dco_decode_flavor(dynamic raw);

  @protected
  GenerateConfig dco_decode_generate_config(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Level dco_decode_level(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, Attachment)> dco_decode_list_record_string_attachment(
    dynamic raw,
  );

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  SystemTime?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    dynamic raw,
  );

  @protected
  Flavor? dco_decode_opt_box_autoadd_flavor(dynamic raw);

  @protected
  Level? dco_decode_opt_box_autoadd_level(dynamic raw);

  @protected
  OrderXType? dco_decode_opt_box_autoadd_order_x_type(dynamic raw);

  @protected
  PdfMetadata? dco_decode_opt_box_autoadd_pdf_metadata(dynamic raw);

  @protected
  OrderXType dco_decode_order_x_type(dynamic raw);

  @protected
  PdfMetadata dco_decode_pdf_metadata(dynamic raw);

  @protected
  (String, Attachment) dco_decode_record_string_attachment(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  FacturXResultFlavor
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor(
    SseDeserializer deserializer,
  );

  @protected
  FacturXResultStringVecU8
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8(
    SseDeserializer deserializer,
  );

  @protected
  FacturXResultVecU8
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
    SseDeserializer deserializer,
  );

  @protected
  SystemTime
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, Attachment> sse_decode_Map_String_attachment_None(
    SseDeserializer deserializer,
  );

  @protected
  FacturXResultFlavor
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor(
    SseDeserializer deserializer,
  );

  @protected
  FacturXResultStringVecU8
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8(
    SseDeserializer deserializer,
  );

  @protected
  FacturXResultVecU8
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
    SseDeserializer deserializer,
  );

  @protected
  SystemTime
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Attachment sse_decode_attachment(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  SystemTime
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    SseDeserializer deserializer,
  );

  @protected
  Flavor sse_decode_box_autoadd_flavor(SseDeserializer deserializer);

  @protected
  GenerateConfig sse_decode_box_autoadd_generate_config(
    SseDeserializer deserializer,
  );

  @protected
  Level sse_decode_box_autoadd_level(SseDeserializer deserializer);

  @protected
  OrderXType sse_decode_box_autoadd_order_x_type(SseDeserializer deserializer);

  @protected
  PdfMetadata sse_decode_box_autoadd_pdf_metadata(SseDeserializer deserializer);

  @protected
  Flavor sse_decode_flavor(SseDeserializer deserializer);

  @protected
  GenerateConfig sse_decode_generate_config(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Level sse_decode_level(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, Attachment)> sse_decode_list_record_string_attachment(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  SystemTime?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    SseDeserializer deserializer,
  );

  @protected
  Flavor? sse_decode_opt_box_autoadd_flavor(SseDeserializer deserializer);

  @protected
  Level? sse_decode_opt_box_autoadd_level(SseDeserializer deserializer);

  @protected
  OrderXType? sse_decode_opt_box_autoadd_order_x_type(
    SseDeserializer deserializer,
  );

  @protected
  PdfMetadata? sse_decode_opt_box_autoadd_pdf_metadata(
    SseDeserializer deserializer,
  );

  @protected
  OrderXType sse_decode_order_x_type(SseDeserializer deserializer);

  @protected
  PdfMetadata sse_decode_pdf_metadata(SseDeserializer deserializer);

  @protected
  (String, Attachment) sse_decode_record_string_attachment(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor(
    FacturXResultFlavor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8(
    FacturXResultStringVecU8 self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
    FacturXResultVecU8 self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    SystemTime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_attachment_None(
    Map<String, Attachment> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor(
    FacturXResultFlavor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8(
    FacturXResultStringVecU8 self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
    FacturXResultVecU8 self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    SystemTime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_attachment(Attachment self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    SystemTime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flavor(Flavor self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_generate_config(
    GenerateConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_level(Level self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_order_x_type(
    OrderXType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pdf_metadata(
    PdfMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flavor(Flavor self, SseSerializer serializer);

  @protected
  void sse_encode_generate_config(
    GenerateConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_level(Level self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_attachment(
    List<(String, Attachment)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    SystemTime? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_flavor(
    Flavor? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_level(Level? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_order_x_type(
    OrderXType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_pdf_metadata(
    PdfMetadata? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_order_x_type(OrderXType self, SseSerializer serializer);

  @protected
  void sse_encode_pdf_metadata(PdfMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_attachment(
    (String, Attachment) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_facturx_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_facturx_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8Ptr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_facturx_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8 =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8Ptr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8Ptr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_facturx_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8 =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8Ptr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8Ptr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_facturx_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8 =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8Ptr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8Ptr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_facturx_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8 =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8Ptr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTimePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_facturx_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTimePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTimePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_facturx_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTimePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
