// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -2054664732;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'facturx',
        ioDirectory: 'rust/core/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<FacturXResultStringVecU8> crateApiExtractXml({
    required List<int> pdfBytes,
    required bool checkXsd,
  });

  Future<FacturXResultVecU8> crateApiGenerateFacturx({
    required List<int> pdfBytes,
    required List<int> xmlBytes,
    required GenerateConfig config,
  });

  Future<FacturXResultFlavor> crateApiGetFlavor({required List<int> xmlBytes});

  Future<Uint8List> crateApiUnpackResultVec({
    required FacturXResultVecU8 result,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FacturXResultFlavor;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FacturXResultFlavor;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FacturXResultFlavorPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FacturXResultStringVecU8;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FacturXResultStringVecU8;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FacturXResultStringVecU8Ptr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FacturXResultVecU8;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FacturXResultVecU8;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FacturXResultVecU8Ptr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SystemTime;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SystemTime;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SystemTimePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<FacturXResultStringVecU8> crateApiExtractXml({
    required List<int> pdfBytes,
    required bool checkXsd,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(pdfBytes, serializer);
          sse_encode_bool(checkXsd, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExtractXmlConstMeta,
        argValues: [pdfBytes, checkXsd],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExtractXmlConstMeta => const TaskConstMeta(
    debugName: "extract_xml",
    argNames: ["pdfBytes", "checkXsd"],
  );

  @override
  Future<FacturXResultVecU8> crateApiGenerateFacturx({
    required List<int> pdfBytes,
    required List<int> xmlBytes,
    required GenerateConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(pdfBytes, serializer);
          sse_encode_list_prim_u_8_loose(xmlBytes, serializer);
          sse_encode_box_autoadd_generate_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGenerateFacturxConstMeta,
        argValues: [pdfBytes, xmlBytes, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateFacturxConstMeta => const TaskConstMeta(
    debugName: "generate_facturx",
    argNames: ["pdfBytes", "xmlBytes", "config"],
  );

  @override
  Future<FacturXResultFlavor> crateApiGetFlavor({required List<int> xmlBytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(xmlBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetFlavorConstMeta,
        argValues: [xmlBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetFlavorConstMeta =>
      const TaskConstMeta(debugName: "get_flavor", argNames: ["xmlBytes"]);

  @override
  Future<Uint8List> crateApiUnpackResultVec({
    required FacturXResultVecU8 result,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
            result,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUnpackResultVecConstMeta,
        argValues: [result],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUnpackResultVecConstMeta =>
      const TaskConstMeta(debugName: "unpack_result_vec", argNames: ["result"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FacturXResultFlavor => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FacturXResultFlavor => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FacturXResultStringVecU8 => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FacturXResultStringVecU8 => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FacturXResultVecU8 => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FacturXResultVecU8 => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SystemTime => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SystemTime => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime;

  @protected
  FacturXResultFlavor
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FacturXResultFlavorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FacturXResultStringVecU8
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FacturXResultStringVecU8Impl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  FacturXResultVecU8
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FacturXResultVecU8Impl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SystemTime
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SystemTimeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Map<String, Attachment> dco_decode_Map_String_attachment_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_attachment(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  FacturXResultFlavor
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FacturXResultFlavorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FacturXResultStringVecU8
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FacturXResultStringVecU8Impl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  FacturXResultVecU8
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FacturXResultVecU8Impl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SystemTime
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SystemTimeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Attachment dco_decode_attachment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Attachment(
      filedata: dco_decode_list_prim_u_8_strict(arr[0]),
      description: dco_decode_opt_String(arr[1]),
      modificationDatetime:
          dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
            arr[2],
          ),
      creationDatetime:
          dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
            arr[3],
          ),
      afrelationship: dco_decode_String(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SystemTime
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
      raw,
    );
  }

  @protected
  Flavor dco_decode_box_autoadd_flavor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flavor(raw);
  }

  @protected
  GenerateConfig dco_decode_box_autoadd_generate_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_generate_config(raw);
  }

  @protected
  Level dco_decode_box_autoadd_level(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_level(raw);
  }

  @protected
  OrderXType dco_decode_box_autoadd_order_x_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_order_x_type(raw);
  }

  @protected
  PdfMetadata dco_decode_box_autoadd_pdf_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pdf_metadata(raw);
  }

  @protected
  Flavor dco_decode_flavor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Flavor.values[raw as int];
  }

  @protected
  GenerateConfig dco_decode_generate_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return GenerateConfig(
      flavor: dco_decode_opt_box_autoadd_flavor(arr[0]),
      level: dco_decode_opt_box_autoadd_level(arr[1]),
      orderxType: dco_decode_opt_box_autoadd_order_x_type(arr[2]),
      checkXsd: dco_decode_bool(arr[3]),
      pdfMetadata: dco_decode_opt_box_autoadd_pdf_metadata(arr[4]),
      lang: dco_decode_opt_String(arr[5]),
      attachments: dco_decode_Map_String_attachment_None(arr[6]),
      afrelationship: dco_decode_String(arr[7]),
      xmpCompression: dco_decode_bool(arr[8]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Level dco_decode_level(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Level.values[raw as int];
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, Attachment)> dco_decode_list_record_string_attachment(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_string_attachment)
        .toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  SystemTime?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
            raw,
          );
  }

  @protected
  Flavor? dco_decode_opt_box_autoadd_flavor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_flavor(raw);
  }

  @protected
  Level? dco_decode_opt_box_autoadd_level(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_level(raw);
  }

  @protected
  OrderXType? dco_decode_opt_box_autoadd_order_x_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_order_x_type(raw);
  }

  @protected
  PdfMetadata? dco_decode_opt_box_autoadd_pdf_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_pdf_metadata(raw);
  }

  @protected
  OrderXType dco_decode_order_x_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OrderXType.values[raw as int];
  }

  @protected
  PdfMetadata dco_decode_pdf_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PdfMetadata(
      author: dco_decode_String(arr[0]),
      keywords: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      subject: dco_decode_String(arr[3]),
    );
  }

  @protected
  (String, Attachment) dco_decode_record_string_attachment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_attachment(arr[1]));
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  FacturXResultFlavor
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FacturXResultFlavorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FacturXResultStringVecU8
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FacturXResultStringVecU8Impl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FacturXResultVecU8
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FacturXResultVecU8Impl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SystemTime
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SystemTimeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Map<String, Attachment> sse_decode_Map_String_attachment_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_attachment(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  FacturXResultFlavor
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FacturXResultFlavorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FacturXResultStringVecU8
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FacturXResultStringVecU8Impl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FacturXResultVecU8
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FacturXResultVecU8Impl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SystemTime
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SystemTimeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Attachment sse_decode_attachment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filedata = sse_decode_list_prim_u_8_strict(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_modificationDatetime =
        sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
          deserializer,
        );
    var var_creationDatetime =
        sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
          deserializer,
        );
    var var_afrelationship = sse_decode_String(deserializer);
    return Attachment(
      filedata: var_filedata,
      description: var_description,
      modificationDatetime: var_modificationDatetime,
      creationDatetime: var_creationDatetime,
      afrelationship: var_afrelationship,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SystemTime
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
      deserializer,
    ));
  }

  @protected
  Flavor sse_decode_box_autoadd_flavor(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flavor(deserializer));
  }

  @protected
  GenerateConfig sse_decode_box_autoadd_generate_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_generate_config(deserializer));
  }

  @protected
  Level sse_decode_box_autoadd_level(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_level(deserializer));
  }

  @protected
  OrderXType sse_decode_box_autoadd_order_x_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_order_x_type(deserializer));
  }

  @protected
  PdfMetadata sse_decode_box_autoadd_pdf_metadata(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pdf_metadata(deserializer));
  }

  @protected
  Flavor sse_decode_flavor(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Flavor.values[inner];
  }

  @protected
  GenerateConfig sse_decode_generate_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_flavor = sse_decode_opt_box_autoadd_flavor(deserializer);
    var var_level = sse_decode_opt_box_autoadd_level(deserializer);
    var var_orderxType = sse_decode_opt_box_autoadd_order_x_type(deserializer);
    var var_checkXsd = sse_decode_bool(deserializer);
    var var_pdfMetadata = sse_decode_opt_box_autoadd_pdf_metadata(deserializer);
    var var_lang = sse_decode_opt_String(deserializer);
    var var_attachments = sse_decode_Map_String_attachment_None(deserializer);
    var var_afrelationship = sse_decode_String(deserializer);
    var var_xmpCompression = sse_decode_bool(deserializer);
    return GenerateConfig(
      flavor: var_flavor,
      level: var_level,
      orderxType: var_orderxType,
      checkXsd: var_checkXsd,
      pdfMetadata: var_pdfMetadata,
      lang: var_lang,
      attachments: var_attachments,
      afrelationship: var_afrelationship,
      xmpCompression: var_xmpCompression,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Level sse_decode_level(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Level.values[inner];
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, Attachment)> sse_decode_list_record_string_attachment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, Attachment)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_attachment(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SystemTime?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  Flavor? sse_decode_opt_box_autoadd_flavor(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_flavor(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Level? sse_decode_opt_box_autoadd_level(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_level(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OrderXType? sse_decode_opt_box_autoadd_order_x_type(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_order_x_type(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PdfMetadata? sse_decode_opt_box_autoadd_pdf_metadata(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_pdf_metadata(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OrderXType sse_decode_order_x_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return OrderXType.values[inner];
  }

  @protected
  PdfMetadata sse_decode_pdf_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_author = sse_decode_String(deserializer);
    var var_keywords = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_subject = sse_decode_String(deserializer);
    return PdfMetadata(
      author: var_author,
      keywords: var_keywords,
      title: var_title,
      subject: var_subject,
    );
  }

  @protected
  (String, Attachment) sse_decode_record_string_attachment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_attachment(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor(
    FacturXResultFlavor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FacturXResultFlavorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8(
    FacturXResultStringVecU8 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FacturXResultStringVecU8Impl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
    FacturXResultVecU8 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FacturXResultVecU8Impl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    SystemTime self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SystemTimeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void sse_encode_Map_String_attachment_None(
    Map<String, Attachment> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_attachment(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultFlavor(
    FacturXResultFlavor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FacturXResultFlavorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultStringVecu8(
    FacturXResultStringVecU8 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FacturXResultStringVecU8Impl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFacturXResultVecu8(
    FacturXResultVecU8 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FacturXResultVecU8Impl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    SystemTime self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SystemTimeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_attachment(Attachment self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.filedata, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
      self.modificationDatetime,
      serializer,
    );
    sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
      self.creationDatetime,
      serializer,
    );
    sse_encode_String(self.afrelationship, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    SystemTime self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
      self,
      serializer,
    );
  }

  @protected
  void sse_encode_box_autoadd_flavor(Flavor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flavor(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_generate_config(
    GenerateConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_generate_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_level(Level self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_level(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_order_x_type(
    OrderXType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_order_x_type(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_pdf_metadata(
    PdfMetadata self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pdf_metadata(self, serializer);
  }

  @protected
  void sse_encode_flavor(Flavor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_generate_config(
    GenerateConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_flavor(self.flavor, serializer);
    sse_encode_opt_box_autoadd_level(self.level, serializer);
    sse_encode_opt_box_autoadd_order_x_type(self.orderxType, serializer);
    sse_encode_bool(self.checkXsd, serializer);
    sse_encode_opt_box_autoadd_pdf_metadata(self.pdfMetadata, serializer);
    sse_encode_opt_String(self.lang, serializer);
    sse_encode_Map_String_attachment_None(self.attachments, serializer);
    sse_encode_String(self.afrelationship, serializer);
    sse_encode_bool(self.xmpCompression, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_level(Level self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_attachment(
    List<(String, Attachment)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_attachment(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
    SystemTime? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSystemTime(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_flavor(
    Flavor? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_flavor(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_level(Level? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_level(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_order_x_type(
    OrderXType? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_order_x_type(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_pdf_metadata(
    PdfMetadata? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_pdf_metadata(self, serializer);
    }
  }

  @protected
  void sse_encode_order_x_type(OrderXType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_pdf_metadata(PdfMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.author, serializer);
    sse_encode_String(self.keywords, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.subject, serializer);
  }

  @protected
  void sse_encode_record_string_attachment(
    (String, Attachment) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_attachment(self.$2, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class FacturXResultFlavorImpl extends RustOpaque
    implements FacturXResultFlavor {
  // Not to be used by end users
  FacturXResultFlavorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FacturXResultFlavorImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_FacturXResultFlavor,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_FacturXResultFlavor,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_FacturXResultFlavorPtr,
  );
}

@sealed
class FacturXResultStringVecU8Impl extends RustOpaque
    implements FacturXResultStringVecU8 {
  // Not to be used by end users
  FacturXResultStringVecU8Impl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FacturXResultStringVecU8Impl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_FacturXResultStringVecU8,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_FacturXResultStringVecU8,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_FacturXResultStringVecU8Ptr,
  );
}

@sealed
class FacturXResultVecU8Impl extends RustOpaque implements FacturXResultVecU8 {
  // Not to be used by end users
  FacturXResultVecU8Impl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FacturXResultVecU8Impl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_FacturXResultVecU8,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_FacturXResultVecU8,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_FacturXResultVecU8Ptr,
  );
}

@sealed
class SystemTimeImpl extends RustOpaque implements SystemTime {
  // Not to be used by end users
  SystemTimeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SystemTimeImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SystemTime,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SystemTime,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SystemTimePtr,
  );
}
