// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Attachment file to be embedded in the PDF
class Attachment {
  final Uint8List filedata;
  final String? description;
  final SystemTime? modificationDatetime;
  final SystemTime? creationDatetime;
  final String afrelationship;

  const Attachment({
    required this.filedata,
    this.description,
    this.modificationDatetime,
    this.creationDatetime,
    required this.afrelationship,
  });

  @override
  int get hashCode =>
      filedata.hashCode ^
      description.hashCode ^
      modificationDatetime.hashCode ^
      creationDatetime.hashCode ^
      afrelationship.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Attachment &&
          runtimeType == other.runtimeType &&
          filedata == other.filedata &&
          description == other.description &&
          modificationDatetime == other.modificationDatetime &&
          creationDatetime == other.creationDatetime &&
          afrelationship == other.afrelationship;
}

/// Represents the flavor/type of the XML document
enum Flavor { facturX, orderX, zugFerd }

/// Configuration for generating Factur-X/Order-X PDF
class GenerateConfig {
  final Flavor? flavor;
  final Level? level;
  final OrderXType? orderxType;
  final bool checkXsd;
  final PdfMetadata? pdfMetadata;
  final String? lang;
  final Map<String, Attachment> attachments;
  final String afrelationship;
  final bool xmpCompression;

  const GenerateConfig({
    this.flavor,
    this.level,
    this.orderxType,
    required this.checkXsd,
    this.pdfMetadata,
    this.lang,
    required this.attachments,
    required this.afrelationship,
    required this.xmpCompression,
  });

  @override
  int get hashCode =>
      flavor.hashCode ^
      level.hashCode ^
      orderxType.hashCode ^
      checkXsd.hashCode ^
      pdfMetadata.hashCode ^
      lang.hashCode ^
      attachments.hashCode ^
      afrelationship.hashCode ^
      xmpCompression.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerateConfig &&
          runtimeType == other.runtimeType &&
          flavor == other.flavor &&
          level == other.level &&
          orderxType == other.orderxType &&
          checkXsd == other.checkXsd &&
          pdfMetadata == other.pdfMetadata &&
          lang == other.lang &&
          attachments == other.attachments &&
          afrelationship == other.afrelationship &&
          xmpCompression == other.xmpCompression;
}

/// Represents the level/profile of the Factur-X or Order-X document
enum Level { minimum, basicWl, basic, en16931, extended, comfort }

/// Represents the type of Order-X document
enum OrderXType { order, orderChange, orderResponse }

/// PDF metadata for the generated document
class PdfMetadata {
  final String author;
  final String keywords;
  final String title;
  final String subject;

  const PdfMetadata({
    required this.author,
    required this.keywords,
    required this.title,
    required this.subject,
  });

  @override
  int get hashCode =>
      author.hashCode ^ keywords.hashCode ^ title.hashCode ^ subject.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PdfMetadata &&
          runtimeType == other.runtimeType &&
          author == other.author &&
          keywords == other.keywords &&
          title == other.title &&
          subject == other.subject;
}
